name: agri_go
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  #  flutter_native_splash: ^1.2.0
  flutter_launcher_icons: ^0.14.3

  srs_authen:
    path: packages/srs_authen
  srs_common:
    path: packages/srs_common
  srs_forum:
    path: packages/srs_forum
  srs_landing:
    path: packages/srs_landing
  srs_notification:
    path: packages/srs_notification
  srs_setting:
    path: packages/srs_setting
  srs_calendar:
    path: packages/srs_calendar
  srs_diary:
    path: packages/srs_diary
  srs_disease:
    path: packages/srs_disease
  srs_transaction:
    path: packages/srs_transaction

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon_android_12.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/