name: srs_common
description: "A new Flutter package project."
publish_to: 'none'
version: 0.0.1
homepage:

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  srs_landing:
    path: ../../packages/srs_landing
  srs_forum:
    path: ../../packages/srs_forum
  srs_authen:
    path: ../../packages/srs_authen
  srs_setting:
    path: ../../packages/srs_setting
  srs_transaction:
    path: ../../packages/srs_transaction


  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  flutter_localization: ^0.3.1
  flutter_smart_dialog: ^4.9.8+7
  get_storage: ^2.1.1
  path_provider: ^2.1.5
  hive: ^2.2.3
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  google_fonts: ^6.2.1
  dropdown_search: ^5.0.6
  font_awesome_flutter: ^10.8.0
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.2
  carousel_slider: ^5.0.0
  connectivity_plus: ^5.0.2
  dio: ^5.5.0+1
  flutter_staggered_animations: ^1.1.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.3.0
  image_picker: ^1.1.2
  awesome_dio_interceptor: ^1.3.0
  curl_logger_dio_interceptor: ^1.0.0
  internet_connection_checker: ^1.0.0+1
  cached_network_image: ^3.4.1
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

