name: srs_common
description: "A new Flutter package project."
publish_to: 'none'
version: 0.0.1
homepage:

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  flutter_localization: ^0.3.1
  flutter_smart_dialog: ^4.9.8+7
  get_storage: ^2.1.1
  path_provider: ^2.1.5
  hive: ^2.2.3
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  google_fonts: ^6.2.1
  dropdown_search: ^5.0.6
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

